# Base settings
theme: jekyll-theme-minimal

# Page settings
title: "Bernhard Bermeitinger"

url: "https://bermeitinger-b.github.io"
baseurl: ""
github_repo: "https://github.com/bermeitinger-b/bermeitinger-b.github.io"

